version: '3'
services:
  rwdb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: dangerous
      MYSQL_DATABASE: realworld #for database crration automatically
    ports:
      - 3306:3306
    volumes:
      - "./data:/var/lib/mysql"